name: absen
description: Absensi ABIYOSOFT.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  sqflite: ^2.3.0
  font_awesome_flutter: ^10.5.0
  table_calendar: ^3.0.9
  lottie: ^2.6.0
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  http: ^1.1.0  
  geolocator: ^10.0.1  
  permission_handler: ^11.0.0
  flutter_map: ^5.0.0
  timezone: ^0.9.2
  google_maps_flutter: ^2.0.8
  geocoding: ^2.1.0
  flutter_calendar_carousel: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/logo1.png
   - assets/logo2.png